export const ActionTypes = {
    SET_IMAGES: 'SET_IMAGES',
    SET_SETTING: 'SET_SETTING',
    SET_ROWS: 'SET_ROWS',
    DELETE_ROW: 'DELETE_ROW',
    CLEAR_ROW: 'CLEAR_ROW',
    UP_ROW: 'UP_ROW',
    DOWN_ROW: 'DOWN_ROW',
    ADD_TOP_ROW: 'ADD_TOP_ROW',
    ADD_BOTTOM_ROW: 'ADD_BOTTOM_ROW',
    RESET_ROWS: 'RESET_ROWS',
    SET_TITLE_DESCRIPTION: 'SET_TITLE_DESCRIPTION'
}